### ISSUE TITLE
vbTab for using ClipBoard

### ISSUE THREAD

**Issue by OlimilO1402** [ws-garcia/VBA-CSV-interface#24]
Hi,
did you know, if you use vbTab (&H9) as a fieldsDelimiter you can also use the ClipBoard to copy data from/to Excel?
Maybe add a code example to your readme in the section "Using the Code". If you are interested you maybe want to have a look at https://github.com/OlimilO1402/XL_ClipboardReader

**Comment by ws-garcia** [comment]
Thanks for taking the time to suggest improvements for CSV Interface! I will be testing code for parsing CSV strings from the clipboard in the documentation shortly. 

I am enthusiastic about the idea since, if there is a way to get text strings from the clipboard, it should be simple to get a set of records and fields. There is a promising potential, to which I will devote emphasis: sorting, in ascending or descending order, the CSV text strings stored in the Windows clipboard.
